replicaCount: 1

image:
  repository: linuxserver/ombi
  tag: stable
  pullPolicy: IfNotPresent

env:
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"
  - name: "TZ"
    value: "Europe/London"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
    #kubernetes.io/tls-acme: "true"
    #kubernetes.io/ingress.class: traefik
  path: /
  hosts:
    - ombi.k.microserver.space

persistence:
  config:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
